-- | Haskell sources inlined verbatim from the dogfood of
-- @playground/expr-evaluator@. Kept in its own module so
-- 'Scenarios.FlowExprEvaluatorDogfood' stays readable — the sources
-- are long and we don't want them drowning the orchestration.
--
-- These are the /correct/ sources (i.e. with the two pretty-parser
-- fixes and the refined simplify law baked in). If any of them stops
-- compiling, stops passing the tests, or stops surviving the parser
-- roundtrip, the scenario fails and the regression is obvious.
module Scenarios.ExprEvaluatorDogfoodSources
  ( syntaxSrc
  , evalSrc
  , simplifySrc
  , prettySrc
  , facadeSrc
  , specSrc
  ) where

import Data.Text (Text)
import qualified Data.Text as T

syntaxSrc :: Text
syntaxSrc = T.unlines
  [ "module Expr.Syntax"
  , "  ( Expr (..)"
  , "  , Error (..)"
  , "  , Env"
  , "  , emptyEnv"
  , "  , extendEnv"
  , "  , lookupVar"
  , "  ) where"
  , ""
  , "import Data.Map.Strict (Map)"
  , "import qualified Data.Map.Strict as Map"
  , ""
  , "data Expr"
  , "  = Lit !Integer"
  , "  | Var !String"
  , "  | Neg !Expr"
  , "  | Add !Expr !Expr"
  , "  | Mul !Expr !Expr"
  , "  deriving stock (Eq, Show)"
  , ""
  , "data Error"
  , "  = UnboundVariable !String"
  , "  deriving stock (Eq, Show)"
  , ""
  , "type Env = Map String Integer"
  , ""
  , "emptyEnv :: Env"
  , "emptyEnv = Map.empty"
  , ""
  , "extendEnv :: String -> Integer -> Env -> Env"
  , "extendEnv = Map.insert"
  , ""
  , "lookupVar :: String -> Env -> Either Error Integer"
  , "lookupVar k env = case Map.lookup k env of"
  , "  Just v  -> Right v"
  , "  Nothing -> Left (UnboundVariable k)"
  ]

evalSrc :: Text
evalSrc = T.unlines
  [ "module Expr.Eval (eval) where"
  , ""
  , "import Expr.Syntax"
  , ""
  , "eval :: Env -> Expr -> Either Error Integer"
  , "eval env = go"
  , "  where"
  , "    go :: Expr -> Either Error Integer"
  , "    go (Lit n)   = Right n"
  , "    go (Var x)   = lookupVar x env"
  , "    go (Neg e)   = negate <$> go e"
  , "    go (Add a b) = (+) <$> go a <*> go b"
  , "    go (Mul a b) = (*) <$> go a <*> go b"
  ]

simplifySrc :: Text
simplifySrc = T.unlines
  [ "module Expr.Simplify (simplify) where"
  , ""
  , "import Expr.Syntax"
  , ""
  , "simplify :: Expr -> Expr"
  , "simplify (Neg e) ="
  , "  case simplify e of"
  , "    Neg inner -> inner"
  , "    Lit n     -> Lit (negate n)"
  , "    e'        -> Neg e'"
  , "simplify (Add a b) ="
  , "  case (simplify a, simplify b) of"
  , "    (Lit 0, y)     -> y"
  , "    (x, Lit 0)     -> x"
  , "    (Lit m, Lit n) -> Lit (m + n)"
  , "    (x, y)         -> Add x y"
  , "simplify (Mul a b) ="
  , "  case (simplify a, simplify b) of"
  , "    (Lit 0, _)     -> Lit 0"
  , "    (_, Lit 0)     -> Lit 0"
  , "    (Lit 1, y)     -> y"
  , "    (x, Lit 1)     -> x"
  , "    (Lit m, Lit n) -> Lit (m * n)"
  , "    (x, y)         -> Mul x y"
  , "simplify e = e"
  ]

-- | The pretty/parser pair. The two design decisions hidden here —
-- never paren-wrap 'Neg', and only treat @(-digits)@ as a literal
-- when the trailing token is @)@ — are the pins that stop the
-- @prop_prettyRoundtrip@ QuickCheck law from finding either of the
-- two counterexamples the original dogfood surfaced.
prettySrc :: Text
prettySrc = T.unlines
  [ "module Expr.Pretty (pretty, parse) where"
  , ""
  , "import Data.Char (isAlpha, isAlphaNum, isDigit, isSpace)"
  , "import Expr.Syntax"
  , ""
  , "pretty :: Expr -> String"
  , "pretty = go 0"
  , "  where"
  , "    go :: Int -> Expr -> String"
  , "    go _ (Lit n)"
  , "      | n < 0     = \"(\" <> show n <> \")\""
  , "      | otherwise = show n"
  , "    go _ (Var x)   = x"
  , "    go _ (Neg e)   = \"-\" <> go 3 e"
  , "    go p (Add a b) = parenIf (p > 0) (go 0 a <> \" + \" <> go 1 b)"
  , "    go p (Mul a b) = parenIf (p > 1) (go 1 a <> \" * \" <> go 2 b)"
  , "    parenIf :: Bool -> String -> String"
  , "    parenIf True  s = \"(\" <> s <> \")\""
  , "    parenIf False s = s"
  , ""
  , "parse :: String -> Maybe Expr"
  , "parse s = case pExpr (skipWS s) of"
  , "  Just (e, rest) | all isSpace rest -> Just e"
  , "  _                                 -> Nothing"
  , ""
  , "type P a = String -> Maybe (a, String)"
  , ""
  , "pExpr :: P Expr"
  , "pExpr s0 = case pTerm s0 of"
  , "  Nothing       -> Nothing"
  , "  Just (t0, r0) -> chainAdd t0 r0"
  , "  where"
  , "    chainAdd acc s = case skipWS s of"
  , "      '+' : rest -> case pTerm (skipWS rest) of"
  , "        Just (t, s') -> chainAdd (Add acc t) s'"
  , "        Nothing      -> Nothing"
  , "      _ -> Just (acc, s)"
  , ""
  , "pTerm :: P Expr"
  , "pTerm s0 = case pFactor s0 of"
  , "  Nothing       -> Nothing"
  , "  Just (f0, r0) -> chainMul f0 r0"
  , "  where"
  , "    chainMul acc s = case skipWS s of"
  , "      '*' : rest -> case pFactor (skipWS rest) of"
  , "        Just (f, s') -> chainMul (Mul acc f) s'"
  , "        Nothing      -> Nothing"
  , "      _ -> Just (acc, s)"
  , ""
  , "pFactor :: P Expr"
  , "pFactor s = case skipWS s of"
  , "  '-' : rest -> case pFactor (skipWS rest) of"
  , "    Just (e, s') -> Just (Neg e, s')"
  , "    Nothing      -> Nothing"
  , "  s'         -> pAtom s'"
  , ""
  , "pAtom :: P Expr"
  , "pAtom s0 = case skipWS s0 of"
  , "  '(' : rest -> case pInsideParens (skipWS rest) of"
  , "    Just (e, afterInner) -> case skipWS afterInner of"
  , "      ')' : afterClose -> Just (e, afterClose)"
  , "      _                -> Nothing"
  , "    Nothing              -> Nothing"
  , "  s' -> case s' of"
  , "    c : _"
  , "      | isDigit c -> pUnsignedLit s'"
  , "      | isAlpha c -> pIdent s'"
  , "    _             -> Nothing"
  , ""
  , "pInsideParens :: P Expr"
  , "pInsideParens s = case s of"
  , "  '-' : rest | isSoleNegLit rest -> pNegLit s"
  , "  _                              -> pExpr s"
  , "  where"
  , "    isSoleNegLit :: String -> Bool"
  , "    isSoleNegLit s0 = case span isDigit s0 of"
  , "      (digits, after) ->"
  , "        not (null digits)"
  , "          && case skipWS after of"
  , "               ')' : _ -> True"
  , "               _       -> False"
  , ""
  , "pNegLit :: P Expr"
  , "pNegLit ('-' : rest) ="
  , "  case span isDigit rest of"
  , "    (digits, after) | not (null digits) ->"
  , "      case readIntegerSafe digits of"
  , "        Just n  -> Just (Lit (negate n), after)"
  , "        Nothing -> Nothing"
  , "    _ -> Nothing"
  , "pNegLit _ = Nothing"
  , ""
  , "pUnsignedLit :: P Expr"
  , "pUnsignedLit s = case span isDigit s of"
  , "  (digits, rest) | not (null digits) ->"
  , "    case readIntegerSafe digits of"
  , "      Just n  -> Just (Lit n, rest)"
  , "      Nothing -> Nothing"
  , "  _ -> Nothing"
  , ""
  , "pIdent :: P Expr"
  , "pIdent (c : rest) | isAlpha c ="
  , "  let (tailPart, rest') = span isAlphaNum rest"
  , "  in Just (Var (c : tailPart), rest')"
  , "pIdent _ = Nothing"
  , ""
  , "skipWS :: String -> String"
  , "skipWS = dropWhile isSpace"
  , ""
  , "readIntegerSafe :: String -> Maybe Integer"
  , "readIntegerSafe []     = Nothing"
  , "readIntegerSafe digits = go 0 digits"
  , "  where"
  , "    go acc []       = Just acc"
  , "    go acc (c : cs)"
  , "      | isDigit c   = go (acc * 10 + toInteger (fromEnum c - fromEnum '0')) cs"
  , "      | otherwise   = Nothing"
  ]

facadeSrc :: Text
facadeSrc = T.unlines
  [ "module Expr"
  , "  ( module Expr.Syntax"
  , "  , module Expr.Eval"
  , "  , module Expr.Simplify"
  , "  , module Expr.Pretty"
  , "  ) where"
  , ""
  , "import Expr.Eval"
  , "import Expr.Pretty"
  , "import Expr.Simplify"
  , "import Expr.Syntax"
  ]

-- | The test-suite body: 18 unit checks + 3 QuickCheck properties.
-- The 'Arbitrary Expr' generator restricts 'Var' names to a shape
-- the parser accepts — widening it would require a matching parser
-- extension, and 'prop_prettyRoundtrip' would start failing.
specSrc :: Text
specSrc = T.unlines
  [ "module Main where"
  , ""
  , "import qualified Data.Map.Strict as Map"
  , "import Expr.Eval      (eval)"
  , "import Expr.Pretty    (parse, pretty)"
  , "import Expr.Simplify  (simplify)"
  , "import Expr.Syntax    (Env, Error, Expr (..))"
  , "import System.Exit    (exitFailure, exitSuccess)"
  , "import Test.QuickCheck"
  , "  ( Arbitrary (..)"
  , "  , Gen"
  , "  , Property"
  , "  , Result (..)"
  , "  , elements"
  , "  , forAll"
  , "  , listOf"
  , "  , oneof"
  , "  , quickCheckWithResult"
  , "  , sized"
  , "  , stdArgs"
  , "  , (===)"
  , "  )"
  , "import qualified Test.QuickCheck as QC"
  , ""
  , "instance Arbitrary Expr where"
  , "  arbitrary = sized go"
  , "    where"
  , "      go :: Int -> Gen Expr"
  , "      go n"
  , "        | n <= 0    = oneof [ Lit <$> arbitrary, Var <$> genVar ]"
  , "        | otherwise = oneof"
  , "            [ Lit <$> arbitrary"
  , "            , Var <$> genVar"
  , "            , Neg <$> go (n `div` 2)"
  , "            , Add <$> go (n `div` 2) <*> go (n `div` 2)"
  , "            , Mul <$> go (n `div` 2) <*> go (n `div` 2)"
  , "            ]"
  , "  shrink (Lit n)   = [ Lit 0 | n /= 0 ]"
  , "  shrink (Var _)   = []"
  , "  shrink (Neg e)   = e : [ Neg e' | e' <- shrink e ]"
  , "  shrink (Add a b) = [a, b] <> [ Add a' b  | a' <- shrink a ]"
  , "                            <> [ Add a  b' | b' <- shrink b ]"
  , "  shrink (Mul a b) = [a, b] <> [ Mul a' b  | a' <- shrink a ]"
  , "                            <> [ Mul a  b' | b' <- shrink b ]"
  , ""
  , "genVar :: Gen String"
  , "genVar = do"
  , "  c  <- elements alphas"
  , "  cs <- listOf (elements alnums)"
  , "  pure (c : cs)"
  , "  where"
  , "    alphas = ['a' .. 'z'] <> ['A' .. 'Z']"
  , "    alnums = alphas <> ['0' .. '9']"
  , ""
  , "genEnv :: Gen Env"
  , "genEnv = do"
  , "  pairs <- listOf ((,) <$> genVar <*> arbitrary)"
  , "  pure (Map.fromList pairs)"
  , ""
  , "prop_prettyRoundtrip :: Expr -> Property"
  , "prop_prettyRoundtrip e = parse (pretty e) === Just e"
  , ""
  , "prop_simplifyPreservesMeaning :: Expr -> Property"
  , "prop_simplifyPreservesMeaning e = forAll genEnv $ \\env ->"
  , "  case (eval env e :: Either Error Integer, eval env (simplify e)) of"
  , "    (Right n, simplified) -> simplified === Right n"
  , "    (Left  _, _)          -> QC.property ()"
  , ""
  , "prop_simplifyIdempotent :: Expr -> Property"
  , "prop_simplifyIdempotent e = simplify (simplify e) === simplify e"
  , ""
  , "runProp :: QC.Testable prop => String -> prop -> IO Bool"
  , "runProp name prop = do"
  , "  res <- quickCheckWithResult stdArgs { QC.chatty = False } prop"
  , "  let ok = case res of Success {} -> True; _ -> False"
  , "  putStrLn ((if ok then \"PASS  \" else \"FAIL  \") <> name)"
  , "  pure ok"
  , ""
  , "main :: IO ()"
  , "main = do"
  , "  propResults <- sequence"
  , "    [ runProp \"prop_prettyRoundtrip\"           prop_prettyRoundtrip"
  , "    , runProp \"prop_simplifyPreservesMeaning\"  prop_simplifyPreservesMeaning"
  , "    , runProp \"prop_simplifyIdempotent\"        prop_simplifyIdempotent"
  , "    ]"
  , "  if and propResults then exitSuccess else exitFailure"
  ]
