name:                 lambda-hm
version:              0.1.0.0
visibility:           public
id:                   lambda-hm-0.1.0.0-inplace
key:                  lambda-hm-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           you@example.com
synopsis:             (describe here)
description:          TODO: describe lambda-hm in one line.
category:             Development
abi:                  inplace
exposed:              True
exposed-modules:
    LambdaHM LambdaHM.Eval LambdaHM.Infer LambdaHM.Pretty
    LambdaHM.Syntax

import-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/build

library-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/build

library-dirs-static:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/build

dynamic-library-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/build

data-dir:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/.

hs-libraries:         HSlambda-hm-0.1.0.0-inplace
depends:              base-4.21.0.0-958c containers-0.7-f896 mtl-2.3.1-b11b
haddock-interfaces:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/doc/html/lambda-hm/lambda-hm.haddock

haddock-html:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/lambda-hm/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/lambda-hm-0.1.0.0/doc/html/lambda-hm
