-- Auto-generated by ghci_quickcheck_export
-- 7 properties from properties.json
module Main where

import Test.QuickCheck
import Expr.Eval
import Expr.Pretty
import Expr.Simplify
import Expr.Syntax

main :: IO ()
main = do
  putStrLn "Running 7 QuickCheck properties..."
  putStr "addRightIdentity: " >> quickCheck (\e -> eval emptyEnv (Add e (Lit 0)) == eval emptyEnv e)
  putStr "mulRightIdentity: " >> quickCheck (\e -> eval emptyEnv (Mul e (Lit 1)) == eval emptyEnv e)
  putStr "negInvolution: " >> quickCheck (\e -> eval emptyEnv (Neg (Neg e)) == eval emptyEnv e)
  putStr "evalRespectsSimplify: " >> quickCheck (\e -> eval emptyEnv (simplify e) == eval emptyEnv e)
  putStr "simplifyIdempotent: " >> quickCheck (\e -> simplify (simplify e) == simplify e)
  putStr "constantFoldAdd: " >> quickCheck (simplify (Add (Lit 3) (Lit 4)) == Lit 7)
  putStr "prettyParseRoundtrip: " >> quickCheck (\e -> parse (pretty e) == Just e)
  putStrLn "All properties checked."
