import { describe, it, expect, afterEach } from "vitest";
import { mkdtempSync, rmSync, existsSync, readFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { handleCreateProject } from "../tools/create-project.js";

describe("handleCreateProject", () => {
  const tmpDirs: string[] = [];

  function mkTmp(): string {
    const d = mkdtempSync(path.join(os.tmpdir(), "create-project-"));
    tmpDirs.push(d);
    return d;
  }

  afterEach(() => {
    for (const d of tmpDirs.splice(0)) {
      try { rmSync(d, { recursive: true, force: true }); } catch { /* ignore */ }
    }
  });

  it("creates a minimal project with defaults (1 PascalCase module, test-suite, cabal.project)", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({ name: "expr-eval", rootDir: root });
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.modules).toEqual(["ExprEval"]);
    expect(result.created).toEqual(
      expect.arrayContaining([
        "expr-eval.cabal",
        "cabal.project",
        path.join("src", "ExprEval.hs"),
        "test/Spec.hs",
      ])
    );
    const cabalPath = path.join(result.projectDir, "expr-eval.cabal");
    expect(existsSync(cabalPath)).toBe(true);
    const cabal = readFileSync(cabalPath, "utf8");
    expect(cabal).toContain("name:               expr-eval");
    expect(cabal).toContain("exposed-modules:\n    ExprEval");
    expect(cabal).toContain("test-suite expr-eval-test");
    expect(cabal).toContain("QuickCheck");
  });

  it("honors explicit modules list with dotted names + creates nested src/ dirs", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({
      name: "expr",
      rootDir: root,
      modules: ["Expr.Syntax", "Expr.Eval"],
    });
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(existsSync(path.join(result.projectDir, "src", "Expr", "Syntax.hs"))).toBe(true);
    expect(existsSync(path.join(result.projectDir, "src", "Expr", "Eval.hs"))).toBe(true);
    const cabal = readFileSync(path.join(result.projectDir, "expr.cabal"), "utf8");
    expect(cabal).toContain("    Expr.Syntax");
    expect(cabal).toContain("    Expr.Eval");
  });

  it("omits test-suite and Spec.hs when with_test_suite=false", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({
      name: "lib-only",
      rootDir: root,
      withTestSuite: false,
    });
    expect(result.success).toBe(true);
    if (!result.success) return;
    const cabal = readFileSync(path.join(result.projectDir, "lib-only.cabal"), "utf8");
    expect(cabal).not.toContain("test-suite");
    expect(existsSync(path.join(result.projectDir, "test", "Spec.hs"))).toBe(false);
  });

  it("fails cleanly when a .cabal already exists at target", async () => {
    const root = mkTmp();
    // First call succeeds.
    const first = await handleCreateProject({ name: "dup", rootDir: root });
    expect(first.success).toBe(true);
    // Second call at the same target must fail — no force, no prompts.
    const second = await handleCreateProject({ name: "dup", rootDir: root });
    expect(second.success).toBe(false);
    if (second.success) return;
    expect(second.error).toMatch(/already exists/i);
    expect(second.hint).toMatch(/ghci_add_modules|different name/i);
  });

  it("produces clean output — no comments, no 'Generated by', no TODO", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({ name: "clean", rootDir: root, modules: ["Lib"] });
    expect(result.success).toBe(true);
    if (!result.success) return;
    const libHs = readFileSync(path.join(result.projectDir, "src", "Lib.hs"), "utf8");
    expect(libHs).toBe("module Lib where\n");
    const spec = readFileSync(path.join(result.projectDir, "test", "Spec.hs"), "utf8");
    expect(spec).not.toMatch(/Generated by/i);
    expect(spec).not.toMatch(/TODO|FIXME/i);
  });

  it("applies custom language when requested", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({
      name: "h2010",
      rootDir: root,
      language: "Haskell2010",
    });
    expect(result.success).toBe(true);
    if (!result.success) return;
    const cabal = readFileSync(path.join(result.projectDir, "h2010.cabal"), "utf8");
    expect(cabal).toContain("default-language: Haskell2010");
  });

  it("appends extra deps beyond base/QuickCheck without duplicating base", async () => {
    const root = mkTmp();
    const result = await handleCreateProject({
      name: "with-deps",
      rootDir: root,
      deps: ["containers", "mtl >= 2.2"],
    });
    expect(result.success).toBe(true);
    if (!result.success) return;
    const cabal = readFileSync(path.join(result.projectDir, "with-deps.cabal"), "utf8");
    expect(cabal).toContain("containers");
    expect(cabal).toContain("mtl >= 2.2");
    const baseCount = (cabal.match(/base >= 4\.20/g) ?? []).length;
    expect(baseCount).toBeGreaterThanOrEqual(1);
  });
});
