name:                 arithmetic-expr
version:              0.1.0.0
visibility:           public
id:                   arithmetic-expr-0.1.0.0-inplace
key:                  arithmetic-expr-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           you@example.com
synopsis:             (describe here)
description:          TODO: describe arithmetic-expr in one line.
category:             Development
abi:                  inplace
exposed:              True
exposed-modules:
    ArithmeticExpr Expr.Eval Expr.Pretty Expr.Simplify Expr.Syntax

import-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/build

library-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/build

library-dirs-static:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/build

dynamic-library-dirs:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/build

data-dir:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/.

hs-libraries:         HSarithmetic-expr-0.1.0.0-inplace
depends:              base-4.21.0.0-958c containers-0.7-f896
haddock-interfaces:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/doc/html/arithmetic-expr/arithmetic-expr.haddock

haddock-html:
    /Users/dlattenero/Personal-Projects/haskell-rules-and-mcp/playground/arithmetic-expr/dist-newstyle-mcp/build/aarch64-osx/ghc-9.12.2/arithmetic-expr-0.1.0.0/doc/html/arithmetic-expr
