-- | @ghc_quickcheck_export@ — materialize a runnable Haskell test
-- file from the persisted QuickCheck property store.
--
-- `ghc_quickcheck` auto-saves passing properties to
-- `.haskell-flows/properties.json`. That file is internal state —
-- not runnable by `cabal test` directly. This tool closes the loop:
-- reads the store, emits a `test/Spec.hs`-shaped Main module with
-- one `runProp` line per property, and writes it to disk at a
-- caller-chosen path.
--
-- Once exported + committed, the project's standard `cabal test`
-- replays every persisted property the same way `ghc_regression`
-- does from inside GHCi — but from CI, without the MCP in the
-- loop.
--
-- Security:
--
-- * Output path routed through 'mkModulePath' so a path-traversal
--   attempt is rejected by the existing boundary validator
--   (CWE-22 defence).
-- * Property text is NOT re-sanitised on write — every stored
--   property passed through 'sanitizeExpression' at capture time,
--   so embedding verbatim is safe.
-- * Generated code is a plain `module Main where`; it never
--   injects cabal / ghc flags the user didn't opt in to.
module HaskellFlows.Tool.QuickCheckExport
  ( handle
  , ExportArgs (..)
  , renderTestFile
  , renderTestFileWith
  , sanitizeLabel
  , modulePathToModule
  , injectTypeAnnotations
    -- * Issue #215 — eta-reduce helper (exported for unit tests)
  , etaReduceLambda
    -- * Issue #198 — signature helpers (exported for unit tests)
  , renderPropSignature
  , splitAtDepthZeroSpaces
  , extractAnnotatedType
    -- * Internals exposed for unit tests
  , generatedHeader
  , scaffoldTestFileHeader
  , exportGuard
    -- * Issue #250 — run-line rendering (exported for unit tests)
  , renderRunLine
  , renderPropBinding
  ) where

import Control.Exception (SomeException, try)
import Data.Aeson
import Data.Aeson.Types (parseEither)
import Data.Char (isAlphaNum, isAsciiLower, isAsciiUpper, isDigit, isAlpha)
import Data.List (nub, sort)
import Data.Maybe (fromMaybe, mapMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import System.Directory (createDirectoryIfMissing, doesFileExist)
import System.FilePath (takeDirectory)

import HaskellFlows.Data.PropertyStore (Store, StoredProperty (..), loadAll)
import HaskellFlows.Mcp.Envelope (ToolResponse)
import qualified HaskellFlows.Mcp.Envelope as Env
import HaskellFlows.Mcp.ParseError (formatParseError)
import HaskellFlows.Mcp.Protocol ()
import qualified HaskellFlows.Tool.QuickCheck as Qc
import HaskellFlows.Types (ProjectDir, mkModulePath, unModulePath, unProjectDir)

-- | #94 Phase C step 6: this module's @descriptor@ was retired
-- when the four legacy property-store tools were merged into
-- 'HaskellFlows.Tool.PropertyStore'. The 'handle' function below
-- is now invoked indirectly via 'Server.dispatchPropertyStore'
-- when the agent calls @ghc_property_store(action=\"export\")@.
-- Behaviour is byte-identical to the legacy @ghc_quickcheck_export@
-- surface.

-- | The leading comment we stamp on every generated file.  Used as
-- a sentinel to tell apart a previously-generated file (safe to
-- overwrite) from a hand-written one (needs 'eaForce').
--
-- Issue #198: updated to the current tool name (@ghc_property_store@).
-- The old @ghc_quickcheck_export@ name was retired in #94 Phase C.
generatedHeader :: Text
generatedHeader = "-- Generated by ghc_property_store."

-- | Header produced by 'HaskellFlows.Tool.CreateProject.testFile' —
-- the scaffold stub written by @ghc_project(action=\"create\")@.
-- Also safe to overwrite with a property-store export (both are
-- MCP-generated; the stub is intentionally replaced by a real suite).
scaffoldTestFileHeader :: Text
scaffoldTestFileHeader = "-- | Scaffolded test suite."

data ExportArgs = ExportArgs
  { eaOutputPath :: !(Maybe Text)
  , eaModule     :: !(Maybe Text)
  -- | #131: bypass the hand-written-file guard.  When 'False'
  -- (default) the export refuses to overwrite a file that does not
  -- start with 'generatedHeader'.  Set to 'True' to proceed anyway.
  , eaForce      :: !Bool
  }
  deriving stock (Show)

instance FromJSON ExportArgs where
  parseJSON = withObject "ExportArgs" $ \o ->
    ExportArgs
      <$> o .:? "output_path"
      <*> o .:? "module"
      <*> (fromMaybe False <$> o .:? "force")

--------------------------------------------------------------------------------
-- handle
--------------------------------------------------------------------------------

handle :: Store -> ProjectDir -> Value -> IO ToolResponse
handle store pd rawArgs = case parseEither parseJSON rawArgs of
  Left err -> pure (formatParseError err)
  Right args -> do
    props <- loadAll store
    let filtered = case eaModule args of
          Nothing -> props
          Just m  -> [ p | p <- props, spModule p == Just m ]
        outRel = maybe "test/Spec.hs" T.unpack (eaOutputPath args)
    case mkModulePath pd outRel of
      Left err -> pure (pathTraversalResult
                          (T.pack ("Invalid output path: " <> show err)))
      Right mp -> do
        -- Resolve the project's library exposed-modules so a property
        -- whose 'spModule' was a test scope (e.g. 'test/Spec.hs') can
        -- still reference library symbols (issue #40). 'libraryExposedModules'
        -- returns @[]@ on any I/O / parse failure so a corrupt or
        -- absent .cabal degrades to the historical behaviour.
        libMods <- Qc.libraryExposedModules pd
        -- Identify the would-be module name for the output file. Any
        -- inferred import that matches it is the file importing
        -- itself — circular and invalid (#40).
        let selfHint = modulePathToModule (T.pack outRel)
            full     = unModulePath mp
            body     = renderTestFileWith selfHint libMods filtered
        -- #131: guard against silently overwriting a hand-written file.
        -- Only bypass when the caller passes force=true or the file
        -- starts with our generated header (safe to regenerate).
        guardResult <- exportGuard full (eaForce args)
        case guardResult of
          Just refusal -> pure refusal
          Nothing -> do
            eRes <- try (do
              createDirectoryIfMissing True (takeDirectory full)
              TIO.writeFile full body) :: IO (Either SomeException ())
            case eRes of
              Left ex -> pure (subprocessResult
                                  (T.pack ("Could not write: " <> show ex)))
              Right _ -> pure (successResult full (length filtered) (length props))
  where
    _ = unProjectDir pd  -- silence unused when path validation is the only use

-- | #131: Check whether writing to 'path' is safe.
--
--   * File does not exist → 'Nothing' (proceed).
--   * File exists + starts with 'generatedHeader' → 'Nothing' (safe to
--     regenerate — the MCP wrote it last time).
--   * File exists + 'force' is 'True' → 'Nothing' (caller opted in).
--   * File exists + no generated header + no force → 'Just' a refusal
--     result so the caller can stop.
--
-- This prevents the critical data-loss scenario where
-- @ghc_property_store(action=\"export\")@ silently overwrites a
-- hand-crafted test suite (issue #131).
exportGuard :: FilePath -> Bool -> IO (Maybe ToolResponse)
exportGuard path force = do
  exists <- doesFileExist path
  if not exists || force
    then pure Nothing
    else do
        eFirst <- try (TIO.readFile path) :: IO (Either SomeException Text)
        case eFirst of
          Left _      -> pure Nothing  -- unreadable → let writeFile handle it
          Right content ->
            if generatedHeader       `T.isPrefixOf` content
               || scaffoldTestFileHeader `T.isPrefixOf` content
              then pure Nothing  -- MCP-generated → safe to overwrite
              else pure (Just (handWrittenGuardResult path))

--------------------------------------------------------------------------------
-- rendering
--------------------------------------------------------------------------------

-- | Emit the full test file contents from a list of stored
-- properties. Imports are derived from the unique set of
-- 'spModule' values that look like source paths
-- (@src/Foo/Bar.hs@) — those are mapped to module names
-- (@Foo.Bar@) and imported.
--
-- Each property becomes one numbered @prop_N@ binding + one line
-- in @main@'s list.
--
-- Compatibility wrapper. Equivalent to
-- @renderTestFileWith Nothing []@. Live callers go through
-- 'renderTestFileWith' so they can pass the project's library
-- exposed-modules + output self-module hint (issue #40).
renderTestFile :: [StoredProperty] -> Text
renderTestFile = renderTestFileWith Nothing []

-- | Issue #40: extended renderer that takes the project's library
-- exposed-modules ('libMods') and the output file's would-be
-- module name ('selfHint').
--
--   * 'libMods' are unioned with the property-derived modules so
--     properties authored in test scope (whose 'spModule' is e.g.
--     @"test/Spec.hs"@) still see every library symbol they
--     reference at compile time.
--   * 'selfHint' (when 'Just') is filtered out of the import list
--     so the generated file never tries to @import Spec@ when it
--     IS @test/Spec.hs@ — that produced the broken circular
--     header reported in the bug.
--
-- 'libMods' empty + 'selfHint' 'Nothing' reproduces the legacy
-- behaviour byte-for-byte; preserved by 'renderTestFile' above.
renderTestFileWith :: Maybe Text -> [Text] -> [StoredProperty] -> Text
renderTestFileWith selfHint libMods props =
  let propMods    = mapMaybe (spModule >=> modulePathToModule) props
      combined    = nub . sort $ libMods <> propMods
      withoutSelf = case selfHint of
        Just sm -> filter (/= sm) combined
        Nothing -> combined
      importLines =
        [ "import " <> m | m <- withoutSelf ]
      propLines =
        concatMap (uncurry renderPropBinding) (zip [1 :: Int ..] props)
      runLines =
        zipWith renderRunLine [1 :: Int ..] props
  in T.unlines $
       [ "-- Generated by ghc_property_store. Do not edit by hand;"
       , "-- regenerate whenever .haskell-flows/properties.json changes."
       , "{-# OPTIONS_GHC -Wno-unused-imports -Wno-missing-signatures #-}"
       , "module Main where"
       , ""
       , "import Test.QuickCheck"
       , "import System.Exit (exitFailure, exitSuccess)"
       ]
       <> importLines
       <> [ ""
          , "main :: IO ()"
          , "main = do"
          , "  rs <- sequence"
          ]
       <> zipWith (\i ln -> "    " <> (if i == 0 then "[ " else ", ") <> ln)
                  [0 :: Int ..] runLines
       <> [ "    ]"
          , "  if and rs then exitSuccess else exitFailure"
          , ""
          , "runProp :: Testable p => String -> p -> IO Bool"
          , "runProp name p = do"
          , "  res <- quickCheckWithResult stdArgs { chatty = False, maxSuccess = 200 } p"
          , "  let ok = case res of Success {} -> True; _ -> False"
          , "  putStrLn ((if ok then \"PASS  \" else \"FAIL  \") <> name)"
          , "  pure ok"
          , ""
          ]
       <> propLines

-- | Issue #198: emit a @prop_N :: T1 -> T2 -> Bool@ type signature
-- line when all parameters carry explicit type annotations.  This
-- avoids @-Wmissing-signatures@ warnings when the exported Spec.hs
-- is compiled by a @cabal test@ stanza that enables @-Wall@.
--
-- The function splits the params string at depth-0 spaces (so that
-- @(xs :: [Int])@ is treated as one token) and extracts each @:: T@
-- annotation.  Returns 'Nothing' when no annotations are present or
-- the extraction fails — the binding is then emitted without a sig.
renderPropSignature :: Int -> Text -> Maybe Text
renderPropSignature i params =
  let label  = "prop_" <> T.pack (show i)
      chunks = splitAtDepthZeroSpaces params
      types  = mapMaybe extractAnnotatedType chunks
  in if null types
       then Nothing
       else Just (label <> " :: " <> T.intercalate " -> " types <> " -> Bool")

-- | Split a params string into individual parameter tokens at
-- depth-0 spaces (spaces not enclosed in parentheses).
-- E.g. @\"(x :: Int) (y :: Int)\"@ → @[\"(x :: Int)\", \"(y :: Int)\"]@.
splitAtDepthZeroSpaces :: Text -> [Text]
splitAtDepthZeroSpaces txt =
  map (T.strip . T.pack) $
    filter (not . null) $
      go (0 :: Int) [] [] (T.unpack txt)
  where
    go _ cur acc []        = acc ++ [reverse cur]
    go 0 cur acc (' ':cs)  = go 0 [] (acc ++ [reverse cur]) cs
    go d cur acc ('(':cs)  = go (d + 1) ('(':cur) acc cs
    go d cur acc (')':cs)  = go (max 0 (d - 1)) (')':cur) acc cs
    go d cur acc (c  :cs)  = go d (c:cur) acc cs

-- | Extract the Haskell type from a single annotated parameter token
-- such as @\"(x :: Int)\"@ or @\"(xs :: [Int])\"@.  Returns 'Nothing'
-- for unannotated bare names.
extractAnnotatedType :: Text -> Maybe Text
extractAnnotatedType chunk =
  case T.stripPrefix "(" (T.strip chunk) of
    Nothing   -> Nothing  -- bare name, no annotation
    Just rest ->
      case T.breakOn " :: " rest of
        (_, "")         -> Nothing  -- no annotation in this token
        (_, afterColon) ->
          let typPart  = T.strip (T.drop 4 afterColon)
              cleaned  = T.strip $
                if ")" `T.isSuffixOf` typPart
                  then T.dropEnd 1 typPart
                  else typPart
          in if T.null cleaned then Nothing else Just cleaned

renderPropBinding :: Int -> StoredProperty -> [Text]
renderPropBinding i sp =
  let label = "prop_" <> T.pack (show i)
      expr  = injectTypeAnnotations (spExpression sp)
  -- Issue #215: emit eta-reduced form "prop_N args = body" rather than
  -- "prop_N = \args -> body" so HLint does not flag "Redundant lambda"
  -- in the exported test file (which blocks CI under -Wall).
  -- Issue #198: prepend a type signature when all parameters carry
  -- explicit type annotations — avoids -Wmissing-signatures.
  in case etaReduceLambda expr of
       Just (params, body) ->
         let binding = label <> " " <> params <> " = " <> body
             mSig    = renderPropSignature i params
         in maybe [binding] (\sig -> [sig, binding]) mSig
       Nothing -> [label <> " = " <> expr]

-- | Issue #215: eta-reduce a lambda expression to its argument-pattern
-- form.  Returns @Just (params, body)@ when @expr@ is a lambda with a
-- \" -> \" at the outermost (depth-0) nesting level; @Nothing@ when
-- the expression is not a lambda or the arrow is not present.
--
-- The search for \" -> \" is parenthesis-aware so parameters with
-- function-type annotations (e.g. @(f :: Int -> Int)@) are kept whole
-- and not split mid-annotation.
--
-- Examples:
--
-- > etaReduceLambda "\\x -> x + 1"
-- >   == Just ("x", "x + 1")
--
-- > etaReduceLambda "\\(x :: Int) -> x + 0 == x"
-- >   == Just ("(x :: Int)", "x + 0 == x")
--
-- > etaReduceLambda "\\(xs :: [Int]) -> reverse (reverse xs) == xs"
-- >   == Just ("(xs :: [Int])", "reverse (reverse xs) == xs")
--
-- > etaReduceLambda "someExpr"
-- >   == Nothing
etaReduceLambda :: Text -> Maybe (Text, Text)
etaReduceLambda expr =
  case T.stripPrefix "\\" (T.strip expr) of
    Nothing   -> Nothing  -- not a lambda
    Just rest ->
      case findTopLevelArrow (T.unpack rest) of
        Nothing  -> Nothing  -- no " -> " at depth 0
        Just pos ->
          let params = T.strip (T.take pos rest)
              body   = T.strip (T.drop (pos + 4) rest)  -- skip " -> "
          in if T.null params || T.null body
               then Nothing
               else Just (params, body)

-- | Find the 0-indexed position of the first \" -> \" that appears at
-- parenthesis-nesting depth 0.  Returns the index of the leading space
-- in \" -> \".
--
-- The depth guard on the first alternative is critical: without it,
-- \" -> \" inside a type annotation like @(f :: Int -> Int)@ would
-- match before the outer lambda arrow.
findTopLevelArrow :: String -> Maybe Int
findTopLevelArrow = go (0 :: Int) (0 :: Int)
  where
    go 0     pos (' ':'-':'>':' ':_) = Just pos   -- found at depth 0
    go depth pos ('(':rest)           = go (depth + 1)       (pos + 1) rest
    go depth pos (')':rest)           = go (max 0 (depth-1)) (pos + 1) rest
    go depth pos (_  :rest)           = go depth             (pos + 1) rest
    go _     _   []                   = Nothing

-- | Inject @:: T@ type annotations into unannotated lambda parameters
-- that are genuinely ambiguous in compiled (non-GHCi) context.
--
-- This is a belt-and-suspenders catch-all for properties persisted
-- before 'Suggest.Rules' started emitting annotated forms (issue #104).
-- Without annotations, polymorphic lambda parameters cause
-- @Ambiguous type variable@ errors when @cabal test@ compiles the
-- exported @Spec.hs@ (GHC's @ExtendedDefaultRules@ only applies
-- inside a GHCi session, not in compiled modules).
--
-- #172 — improved heuristic (three-tier):
--
--  1. Parameters whose name ends in @s@ and contains only identifier
--     chars (@xs@, @ys@, @vals@ …) are annotated @:: [Int]@ — these are
--     almost always list variables in QuickCheck properties.
--
--  2. Parameters that appear in the expression body as an argument to a
--     named function (e.g. @reverseStr x@, @T.pack s@) are left
--     unannotated — their type is constrained by the callee and injecting
--     @:: Int@ would produce a type error.  Detection: the parameter is
--     preceded in the body by a space and then a letter, digit, or
--     closing paren (e.g. @"reverseStr x"@ matches; @"x + y"@ does not).
--
--  3. All remaining parameters (e.g. @x@, @y@ used only in operator
--     expressions like @x + y@) are annotated @:: Int@ as the safe
--     default for arithmetic ambiguity.
--
-- Already-annotated parameters (those whose param block contains @::@)
-- pass through unchanged. Only the outermost lambda head is examined;
-- inner lambdas in the body are left untouched.
injectTypeAnnotations :: Text -> Text
injectTypeAnnotations expr =
  case T.stripPrefix "\\" (T.strip expr) of
    Nothing   -> expr   -- not a lambda
    Just rest ->
      case T.breakOn " -> " rest of
        (_, "")          -> expr  -- no lambda arrow found
        (paramPart, arrowAndBody)
          | "::" `T.isInfixOf` paramPart -> expr  -- already annotated
          | otherwise ->
              let params        = filter (not . T.null) (T.words paramPart)
                  exprBody      = T.drop 4 arrowAndBody  -- strip " -> "
                  bodyWithArrow = T.drop 1 arrowAndBody  -- for output
                  annotated     = map (`annotateOne` exprBody) params
              in "\\" <> T.intercalate " " annotated <> " " <> bodyWithArrow
  where
    annotateOne p exprBody
      | "(" `T.isPrefixOf` p       = p  -- already wrapped / annotated
      | T.null p                   = p
      | isListParam p              = "(" <> p <> " :: [Int])"
      | isConstrainedBy p exprBody = p  -- #172: type determined by caller
      | otherwise                  = "(" <> p <> " :: Int)"

    -- Names ending in 's' composed of identifier chars → list params.
    isListParam p =
      T.length p >= 2
        && T.last p == 's'
        && T.all (\c -> isAlpha c || c == '_' || c == '\'') p

    -- Does 'p' appear as an argument to a named function in 'body'?
    -- True when any occurrence of " p" is immediately preceded by a
    -- letter, digit, ')' or '\'' — meaning 'p' follows a named callee.
    -- Scans all occurrences via repeated T.breakOn.
    isConstrainedBy p = go
      where
        pat = " " <> p
        go txt = case T.breakOn pat txt of
          (_, "")     -> False
          (pre, rest) ->
            let prevIsTyping = case T.uncons (T.reverse pre) of
                  Just (c, _) -> isAlpha c || isDigit c || c == ')' || c == '\''
                  Nothing     -> False
                remaining = T.drop (T.length pat) rest
            in prevIsTyping || go remaining

renderRunLine :: Int -> StoredProperty -> Text
renderRunLine i sp =
  let label = "prop_" <> T.pack (show i)
      -- Issue #250: derive display name from properly-formatted module
      -- name (Foo.Bar) rather than the raw path (src_Foo_Bar_hs).
      -- Falls back to the sequence label when no module is stored or
      -- the path does not follow the src/Mod/Name.hs convention.
      displayName = case spModule sp >>= modulePathToModule of
        Just modName -> sanitizeLabel (modName <> "_prop_" <> T.pack (show i))
        Nothing      -> case spModule sp of
          Just m | not (T.null m) ->
            -- Non-standard path: strip leading dir + extension and
            -- use as best-effort prefix so users still get context.
            let stripped = T.dropEnd 3 $   -- drop .hs
                           last' m $        -- last path segment
                           T.splitOn "/" m
            in sanitizeLabel (stripped <> "_prop_" <> T.pack (show i))
          _           -> label
  in "runProp \"" <> displayName <> "\" " <> label
  where
    -- Total version of 'last': pattern-match on the reversed list.
    last' fallback xs = case reverse xs of
      []    -> fallback
      (x:_) -> x

-- | Sanitise a label for safe embedding in a Haskell string literal.
-- Rules:
--
-- * CR / LF → space (a newline would terminate the string literal).
-- * Collapse whitespace into single underscore.
-- * Keep alnum + underscore + hyphen; replace everything else with
--   underscore.
-- * Strip leading/trailing underscores.
-- * Fallback to @property@ if the result is empty.
sanitizeLabel :: Text -> Text
sanitizeLabel raw =
  let noLines   = T.map (\c -> if c == '\n' || c == '\r' then ' ' else c) raw
      collapsed = T.intercalate "_" (T.words noLines)
      safe      = T.map (\c -> if isAlphaNum c || c == '_' || c == '-' then c else '_') collapsed
      trimmed   = T.dropAround (\c -> c == '_' || c == '-') safe
  in if T.null trimmed then "property" else trimmed

-- | Map a source path like @src/Foo/Bar.hs@ to a module name
-- @Foo.Bar@. Returns 'Nothing' when the path does not match the
-- convention (we cannot know the right import line without it).
--
-- BUG-02 fix: historically this function only stripped @src@ /
-- @lib@ as leading directories. Test-only helper modules live
-- under @test/@ (e.g. @test/Gen.hs@ containing @module Gen@) and
-- were mis-mapped to @test.Gen@ — a lowercase first segment that
-- is not a valid Haskell module name, so the generated Spec.hs
-- failed to compile. Strip @test@ too, plus every segment must
-- start with an uppercase letter; otherwise return 'Nothing' so
-- the renderer simply omits the bad import rather than emit
-- broken Haskell.
modulePathToModule :: Text -> Maybe Text
modulePathToModule raw
  | not (".hs" `T.isSuffixOf` raw) = Nothing
  | otherwise =
      let noExt  = T.dropEnd 3 raw
          parts  = T.splitOn "/" noExt
          -- drop a leading sources-dir name. 'src'/'lib' are the
          -- library conventions; 'test' covers test-suite helpers.
          -- We also drop 'app' for executable mains, though those
          -- are typically 'module Main' and do not import cleanly.
          core   = case parts of
            (p:rest) | p `elem` ["src", "lib", "test", "app"] -> rest
            _                                                  -> parts
      in if null core || not (all segmentIsUppercaseHead core)
           then Nothing
           else let dotted = T.intercalate "." core
                in if T.null dotted then Nothing else Just dotted

-- | A Haskell module-name segment must start with an uppercase
-- letter and contain only identifier-safe characters. Anything
-- else (spaces, kebab-case, lowercase dirs like @support@) is
-- rejected.
segmentIsUppercaseHead :: Text -> Bool
segmentIsUppercaseHead seg = case T.uncons seg of
  Just (c, rest) -> isAsciiUpper c && T.all idChar rest
  Nothing        -> False
  where
    idChar ch =
         isAsciiUpper ch
      || isAsciiLower ch
      || isDigit      ch
      || ch == '_' || ch == '\''

-- | Tiny helper to chain Maybe through pure functions.
(>=>) :: (a -> Maybe b) -> (b -> Maybe c) -> a -> Maybe c
f >=> g = \x -> f x >>= g
{-# INLINE (>=>) #-}

--------------------------------------------------------------------------------
-- response shaping
--------------------------------------------------------------------------------

-- | Issue #90 Phase C: rendered Spec.hs file → status='ok' with
-- the on-disk path + counts under 'result'.
successResult :: FilePath -> Int -> Int -> ToolResponse
successResult path written total =
  Env.mkOk (object
    [ "output_path"        .= T.pack path
    , "properties_written" .= written
    , "total_persisted"    .= total
    , "hint"
        .= ( "Commit the generated file and add QuickCheck to the \
             \test-suite via ghc_deps. `cabal test` will replay \
             \every property as a regression gate." :: Text )
    ])


-- | Issue #90 Phase C: 'mkModulePath' rejected the output path.
pathTraversalResult :: Text -> ToolResponse
pathTraversalResult msg =
  Env.mkRefused (Env.mkErrorEnvelope Env.PathTraversal msg)

-- | #131: the target file exists and does not carry our generated
-- header — refuse to overwrite it without an explicit 'force=true'.
handWrittenGuardResult :: FilePath -> ToolResponse
handWrittenGuardResult path =
  let msg =
        "Refusing to overwrite '" <> T.pack path <> "': the file exists \
        \and does not appear to have been generated by \
        \ghc_property_store. Pass force=true to overwrite it anyway, \
        \or choose a different output_path."
      remediation =
        "Use output_path to write to a separate file (e.g. \
        \\"test/SpecGenerated.hs\"), or pass force=true if you \
        \intentionally want to replace the existing file."
      err = (Env.mkErrorEnvelope Env.HandWrittenFileGuard msg)
              { Env.eeRemediation = Just remediation }
  in Env.mkRefused err

-- | Issue #90 Phase C: filesystem write failure.
subprocessResult :: Text -> ToolResponse
subprocessResult msg =
  Env.mkFailed (Env.mkErrorEnvelope Env.SubprocessError msg)
