/**
 * ghci_quickcheck_export — Generate a Haskell test file from saved properties.
 * Reads properties.json and creates a runnable QuickCheck test suite.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { ToolContext } from "./registry.js";
import { getAllProperties, getModuleProperties } from "../property-store.js";
import { parseCabalModules } from "../parsers/cabal-parser.js";

export async function handleExportTests(
  projectDir: string,
  args: { output_path?: string; module?: string }
): Promise<string> {
  const properties = args.module
    ? await getModuleProperties(projectDir, args.module)
    : await getAllProperties(projectDir);

  if (properties.length === 0) {
    return JSON.stringify({
      success: false,
      error: "No saved properties found. Run ghci_quickcheck to build up the property store.",
    });
  }

  // Collect unique modules referenced by properties
  const moduleSet = new Set<string>();
  for (const p of properties) {
    if (p.module && p.module !== "unknown") {
      // Convert file path to module name: "src/Expr/Eval.hs" → "Expr.Eval"
      const modName = p.module
        .replace(/^src\//, "")
        .replace(/\.hs$/, "")
        .replace(/\//g, ".");
      moduleSet.add(modName);
    }
  }

  // Also get all library modules from .cabal for completeness
  try {
    const cabalMods = await parseCabalModules(projectDir);
    for (const m of cabalMods.library) moduleSet.add(m);
  } catch { /* non-fatal */ }

  const imports = [...moduleSet].sort().map(m => `import ${m}`).join("\n");

  // Generate test file
  const propertyLines = properties.map((p, i) => {
    const label = p.law ?? p.functionName ?? `property_${i + 1}`;
    const safeLabel = label.replace(/"/g, '\\"');
    return `  putStr "${safeLabel}: " >> quickCheck (${p.property})`;
  }).join("\n");

  const testContent = `-- Auto-generated by ghci_quickcheck_export
-- ${properties.length} properties from properties.json
module Main where

import Test.QuickCheck
${imports}

main :: IO ()
main = do
  putStrLn "Running ${properties.length} QuickCheck properties..."
${propertyLines}
  putStrLn "All properties checked."
`;

  const outputPath = args.output_path ?? "test/Spec.hs";
  const absPath = path.resolve(projectDir, outputPath);

  // Ensure directory exists
  const dir = path.dirname(absPath);
  const { mkdir } = await import("node:fs/promises");
  await mkdir(dir, { recursive: true });

  await writeFile(absPath, testContent, "utf-8");

  return JSON.stringify({
    success: true,
    outputPath,
    propertyCount: properties.length,
    modules: [...moduleSet].sort(),
    _nextStep: `Test file written to ${outputPath}. Add a test-suite stanza to your .cabal file to run with 'cabal test'.`,
  });
}

export function register(server: McpServer, ctx: ToolContext): void {
  server.tool(
    "ghci_quickcheck_export",
    "Export saved QuickCheck properties to a Haskell test file (.hs). " +
      "Reads properties.json and generates a runnable test suite. " +
      "Use after development to create persistent tests for CI/CD.",
    {
      output_path: z.string().optional().describe(
        'Output file path. Default: "test/Spec.hs"'
      ),
      module: z.string().optional().describe(
        "Filter properties by module path. If omitted, exports all properties."
      ),
    },
    async ({ output_path, module: mod }) => {
      const result = await handleExportTests(ctx.getProjectDir(), { output_path, module: mod });
      return { content: [{ type: "text" as const, text: result }] };
    }
  );
}
