/**
 * ghci_quickcheck_export — Generate a Haskell test file from saved properties.
 * Reads properties.json and creates a runnable QuickCheck test suite.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { type ToolContext, registerStrictTool } from "./registry.js";
import { getActiveProperties, getActiveModuleProperties } from "../property-store.js";
import { parseCabalModules } from "../parsers/cabal-parser.js";
import { handleCabalTest } from "./test.js";
import { handleValidateCabal } from "./validate-cabal.js";
import { validatePropertyText } from "../parsers/property-validator.js";

export async function handleExportTests(
  projectDir: string,
  args: { output_path?: string; module?: string; validate_test_suite?: boolean; only_passing?: boolean }
): Promise<string> {
  // By default, only export active (non-deprecated) properties
  const properties = args.module
    ? await getActiveModuleProperties(projectDir, args.module)
    : await getActiveProperties(projectDir);

  if (properties.length === 0) {
    return JSON.stringify({
      success: false,
      error: "No saved properties found. Run ghci_quickcheck to build up the property store.",
    });
  }

  // Drop trivially-true properties that provide no signal.
  // e.g. `\x -> True`, `\_ -> True`, `const True`
  const nonTrivial = properties.filter((p) => !isTrivialProperty(p.property));
  const dropped = properties.length - nonTrivial.length;

  if (nonTrivial.length === 0) {
    return JSON.stringify({
      success: false,
      error:
        "All saved properties are trivially true (e.g. `\\x -> True`). " +
        "Add meaningful QuickCheck properties before exporting.",
      droppedTrivial: dropped,
    });
  }

  const invalidProperties = nonTrivial
    .map((p) => ({
      property: p.property,
      module: p.tests_module ?? p.module,
      issues: validatePropertyText(p.property).issues,
    }))
    .filter((entry) => entry.issues.length > 0);

  if (invalidProperties.length > 0) {
    return JSON.stringify({
      success: false,
      error:
        "Property store contains invalid entries that are unsafe to export. " +
        "Use ghci_property_lifecycle(action='deprecate'|'remove') to clean them.",
      invalidCount: invalidProperties.length,
      invalidProperties,
      _nextStep:
        "Deprecate/remove invalid properties, then rerun ghci_quickcheck to store corrected versions before exporting.",
    });
  }

  // Collect unique library module names referenced by properties
  const moduleSet = new Set<string>();
  for (const p of nonTrivial) {
    if (p.module && p.module !== "unknown") {
      const modName = p.module
        .replace(/^src\//, "")
        .replace(/\.hs$/, "")
        .replace(/\//g, ".");
      moduleSet.add(modName);
    }
  }

  // Also get all library modules from .cabal for completeness
  try {
    const cabalMods = await parseCabalModules(projectDir);
    for (const m of cabalMods.library) moduleSet.add(m);
  } catch { /* non-fatal */ }

  const qualifiedImports = detectQualifiedImports(nonTrivial.map((p) => p.property));

  const imports = [
    ...[...moduleSet].sort().map((m) => `import ${m}`),
    ...qualifiedImports,
  ].join("\n");

  // Generate test file
  const propertyLines = nonTrivial.map((p, i) => {
    const label = p.law ?? p.functionName ?? `property_${i + 1}`;
    const safeLabel = label.replace(/"/g, '\\"');
    const normalizedProperty = normalizePropertyForExport(p.property);
    return `  putStr "${safeLabel}: " >> quickCheck (${normalizedProperty})`;
  }).join("\n");

  const testContent = `-- Auto-generated by ghci_quickcheck_export
-- ${nonTrivial.length} properties from properties.json${dropped > 0 ? ` (${dropped} trivial propert${dropped === 1 ? "y" : "ies"} dropped)` : ""}
module Main where

import Test.QuickCheck
${imports}

main :: IO ()
main = do
  putStrLn "Running ${nonTrivial.length} QuickCheck properties..."
${propertyLines}
  putStrLn "All properties checked."
`;

  const outputPath = args.output_path ?? "test/Spec.hs";
  const absPath = path.resolve(projectDir, outputPath);

  // Ensure directory exists
  const dir = path.dirname(absPath);
  const { mkdir } = await import("node:fs/promises");
  await mkdir(dir, { recursive: true });

  await writeFile(absPath, testContent, "utf-8");

  const validateTestSuite = args.validate_test_suite ?? true;
  let testRun:
    | {
        success: boolean;
        summary: string;
        command?: string;
        errors?: unknown[];
        warnings?: unknown[];
      }
    | undefined;

  if (validateTestSuite) {
    const validationResult = JSON.parse(await handleValidateCabal(projectDir));
    if (validationResult.success === false) {
      return JSON.stringify({
        success: false,
        outputPath,
        propertyCount: nonTrivial.length,
        error: "Test suite validation failed before cabal_test.",
        validation: validationResult,
      });
    }

    const testResult = JSON.parse(await handleCabalTest(projectDir, {}));
    testRun = {
      success: testResult.success,
      summary: testResult.summary,
      command: testResult.command,
      errors: testResult.errors,
      warnings: testResult.warnings,
    };
  }

  return JSON.stringify({
    success: true,
    outputPath,
    propertyCount: nonTrivial.length,
    ...(dropped > 0 ? { droppedTrivial: dropped } : {}),
    modules: [...moduleSet].sort(),
    ...(testRun ? { testRun } : {}),
    _nextStep: validateTestSuite
      ? `Test file written to ${outputPath}. Review testRun above, then use cabal_test for future re-runs.`
      : `Test file written to ${outputPath}. Run cabal_test to validate the generated test-suite.`,
  });
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Detect whether a QuickCheck property string is trivially true and provides
 * no real test coverage.  Matches patterns like:
 *   `\x -> True`   `\_ -> True`   `\x y -> True`   `const True`
 */
export function isTrivialProperty(prop: string): boolean {
  const s = prop.trim();
  // Lambda that always returns True
  if (/^\\[^-]*->\s*True\s*$/.test(s)) return true;
  // Point-free: const True
  if (/^const\s+True\s*$/.test(s)) return true;
  return false;
}

/**
 * Normalize exported property text so the generated Spec.hs remains compilable.
 *
 * Wildcard lambdas like `\_ -> ...` may become ambiguous when exported to a
 * standalone QuickCheck file, so we attach a concrete function type.
 */
export function normalizePropertyForExport(prop: string): string {
  const trimmed = prop.trim();
  const wildcardLambdaPattern = /^\\[^-]*_[^-]*->/;

  if (wildcardLambdaPattern.test(trimmed)) {
    return `(${trimmed} :: () -> Bool)`;
  }

  return trimmed;
}

/**
 * Scan property strings for usages of common qualified modules and return the
 * necessary import lines.  This prevents compilation errors in the exported
 * Spec.hs when properties reference e.g. `Map.empty` or `Set.fromList`.
 */
export function detectQualifiedImports(properties: string[]): string[] {
  const combined = properties.join(" ");
  const imports: string[] = [];

  if (/\bMap\./.test(combined)) {
    imports.push("import qualified Data.Map.Strict as Map");
  }
  if (/\bSet\./.test(combined)) {
    imports.push("import qualified Data.Set as Set");
  }
  if (/\bSeq\./.test(combined)) {
    imports.push("import qualified Data.Sequence as Seq");
  }
  if (/\bV\./.test(combined) || /\bVector\./.test(combined)) {
    imports.push("import qualified Data.Vector as Vector");
  }
  if (/\bNonEmpty\./.test(combined)) {
    imports.push("import qualified Data.List.NonEmpty as NonEmpty");
  }
  if (/\bT\./.test(combined) || /\bText\./.test(combined)) {
    imports.push("import qualified Data.Text as Text");
  }

  return imports;
}

export function register(server: McpServer, ctx: ToolContext): void {
  registerStrictTool(server, ctx, 
    "ghci_quickcheck_export",
    "Export saved QuickCheck properties to a Haskell test file (.hs). " +
      "Reads properties.json and generates a runnable test suite. " +
      "Use after development to create persistent tests for CI/CD.",
    {
      output_path: z.string().optional().describe(
        'Output file path. Default: "test/Spec.hs"'
      ),
      module: z.string().optional().describe(
        "Filter properties by module path. If omitted, exports all properties."
      ),
      validate_test_suite: z.boolean().optional().describe(
        "If true (default), run cabal_test after writing the exported test file and report the result."
      ),
      only_passing: z.boolean().optional().describe(
        "If true (default), only export active (non-deprecated) properties. " +
        "Deprecated properties are automatically filtered out to prevent exporting obsolete tests."
      ),
    },
    async ({ output_path, module: mod, validate_test_suite, only_passing }) => {
      const result = await handleExportTests(ctx.getProjectDir(), {
        output_path,
        module: mod,
        validate_test_suite,
        only_passing,
      });
      return { content: [{ type: "text" as const, text: result }] };
    }
  );
}
